### ISSUE TITLE
PAE file is not created for alphafold monomer model runs

### ISSUE THREAD

**Issue by Phage-structure-geek** [mattarnoldbio/alphapickle#5]
Hi!

Thanks for creating this tool. Very useful for those of us who runs alphafold locally and takes it to its limits - long sequences and large multimers.

I first posted a question about why the program cannot find PAE model data in pkl files created by the monomer model run (AF v. 2.2.0), but then found your comments here: https://github.com/deepmind/alphafold/issues/92

So, I am running AF with the monomer_ptm model and all is good now.

Thanks,

Petr

**Comment by mattarnoldbio** [comment]
Hi Petr,

Thanks for pointing this out! Haven't done any testing with v>2.1.0 yet so I'll look into this next week. The error message you're seeing is one that I have written so the chances are I just need to reformat something slightly. I don't have access to a 2.2.0 build at the moment to generate a sample pickle file. Would you mind sending me one of yours to test the fix on? My email is m[dot]arnold[dot]1[at]research[dot]gla[dot]ac[dot]uk. Sharing via Google drive or OneDrive usually works alright.

Cheers

Matt

**Comment by Phage-structure-geek** [comment]
Hi Matt,
The AF v. 2.2.0 default monomer model pkl files do not contain PAE data for some reason. Your program warns the user about it, so it works as expected. The monomer_ptm does contain PAE data and your program outputs everything fine, so all is good.
Petr
P.S. The AF github page states that the monomer model is more accurate than the monomer_ptm model and I am guessing that was the reason for making the less output-informative model a default one.

**Comment by mattarnoldbio** [comment]
Hi Petr... thanks for clearing this up. I suppose this is the trade-off that you have to make then! Out of interest, have you tried running with PTM models? If so, does your accuracy (pLDDT) take a hit?
