### ISSUE TITLE
No matching distribution found for blas==1.0

### ISSUE THREAD

**Issue by zjq1011** [mattarnoldbio/alphapickle#8]
I am using python 3.10, and error was 
Could not find a version that satisfies the requirement blas==1.0 (from versions: none)
Do I need to install 3.9 and create a virtual environment in that version?
Thanks.

**Comment by mattarnoldbio** [comment]
Hi Jiaqiao,
At the moment python 3.10 is not supported and I am afraid I don't know when I will get around to adding support. A python environment with 3.9 in would work. The other option (depending on the specifics of what you are doing) is to use the [Colab notebook](https://colab.research.google.com/github/mattarnoldbio/alphapickle/blob/main/AlphaPickle.ipynb) that I have written.
